export default {
    "code": 200,
    "timestamp": 1518314627630,
    "result": {
        "role": {"DEPT_ID": 37, "ROLE_ID": "eb2388f307d14481a57463e3dc1df49c", "ROLE_NAME": "测试角色名称"},
        "menus": [51, 34, 1, 29, 48, 8, 50, 52, 49],
        "rootMenu": [{
            "menu_id": 29,
            "menu_name": "首页",
            "menu_url": "/home/index",
            "menu_fid": null,
            "childMenus": [{
                "menu_id": 33,
                "menu_name": "重置密码",
                "menu_url": "/home/resetPassword",
                "menu_fid": 29,
                "childMenus": null,
                "menu_order": 4,
                "menu_action": 1,
                "menu_sign": null
            }, {
                "menu_id": 34,
                "menu_name": "用户中心",
                "menu_url": "/home/userCenter",
                "menu_fid": 29,
                "childMenus": null,
                "menu_order": 5,
                "menu_action": 1,
                "menu_sign": 1
            }],
            "menu_order": 1,
            "menu_action": 1,
            "menu_sign": 1
        }, {
            "menu_id": 1,
            "menu_name": "需求管理",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": [{
                "menu_id": 39,
                "menu_name": "业务需求",
                "menu_url": "/home/ywxq",
                "menu_fid": 1,
                "childMenus": null,
                "menu_order": 1,
                "menu_action": 1,
                "menu_sign": null
            }, {
                "menu_id": 8,
                "menu_name": "基础建设",
                "menu_url": "/home/jcjs",
                "menu_fid": 1,
                "childMenus": [{
                    "menu_id": 52,
                    "menu_name": "完成",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": 1
                }, {
                    "menu_id": 51,
                    "menu_name": "拆分任务",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": 1
                }, {
                    "menu_id": 50,
                    "menu_name": "转接",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": 1
                }, {
                    "menu_id": 49,
                    "menu_name": "挂起",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": 1
                }, {
                    "menu_id": 48,
                    "menu_name": "驳回",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": 1
                }, {
                    "menu_id": 47,
                    "menu_name": "分配",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": null
                }, {
                    "menu_id": 46,
                    "menu_name": "新建变更",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": null
                }, {
                    "menu_id": 45,
                    "menu_name": "需求内变更",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": null
                }, {
                    "menu_id": 44,
                    "menu_name": "立项",
                    "menu_url": null,
                    "menu_fid": 8,
                    "childMenus": null,
                    "menu_order": 1,
                    "menu_action": 0,
                    "menu_sign": null
                }],
                "menu_order": 3,
                "menu_action": 1,
                "menu_sign": 1
            }],
            "menu_order": 2,
            "menu_action": 1,
            "menu_sign": 1
        }, {
            "menu_id": 2,
            "menu_name": "上线管理",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": [{
                "menu_id": 60,
                "menu_name": "上线确认",
                "menu_url": null,
                "menu_fid": 2,
                "childMenus": null,
                "menu_order": 1,
                "menu_action": 0,
                "menu_sign": null
            }, {
                "menu_id": 59,
                "menu_name": "上线申请",
                "menu_url": null,
                "menu_fid": 2,
                "childMenus": null,
                "menu_order": 1,
                "menu_action": 0,
                "menu_sign": null
            }],
            "menu_order": 3,
            "menu_action": 1,
            "menu_sign": null
        }, {
            "menu_id": 3,
            "menu_name": "问题管理",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": [{
                "menu_id": 41,
                "menu_name": "故障列表",
                "menu_url": "/home/errorlist",
                "menu_fid": 3,
                "childMenus": null,
                "menu_order": 1,
                "menu_action": 1,
                "menu_sign": null
            }, {
                "menu_id": 42,
                "menu_name": "BUG列表",
                "menu_url": "/home/buglist",
                "menu_fid": 3,
                "childMenus": null,
                "menu_order": 2,
                "menu_action": 1,
                "menu_sign": null
            }],
            "menu_order": 4,
            "menu_action": 1,
            "menu_sign": null
        }, {
            "menu_id": 4,
            "menu_name": "统计分析",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": null,
            "menu_order": 5,
            "menu_action": 1,
            "menu_sign": null
        }, {
            "menu_id": 5,
            "menu_name": "实时统计",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": null,
            "menu_order": 6,
            "menu_action": 1,
            "menu_sign": null
        }, {
            "menu_id": 6,
            "menu_name": "版本库",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": null,
            "menu_order": 7,
            "menu_action": 1,
            "menu_sign": null
        }, {
            "menu_id": 7,
            "menu_name": "资料库",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": null,
            "menu_order": 8,
            "menu_action": 1,
            "menu_sign": null
        }, {
            "menu_id": 35,
            "menu_name": "权限管理",
            "menu_url": null,
            "menu_fid": null,
            "childMenus": [{
                "menu_id": 36,
                "menu_name": "人员配置",
                "menu_url": "/home/rolelist",
                "menu_fid": 35,
                "childMenus": null,
                "menu_order": 1,
                "menu_action": 1,
                "menu_sign": null
            }, {
                "menu_id": 37,
                "menu_name": "权限列表",
                "menu_url": "/home/power",
                "menu_fid": 35,
                "childMenus": null,
                "menu_order": 2,
                "menu_action": 1,
                "menu_sign": null
            }, {
                "menu_id": 38,
                "menu_name": "角色管理",
                "menu_url": "/home/rolemanage",
                "menu_fid": 35,
                "childMenus": null,
                "menu_order": 3,
                "menu_action": 1,
                "menu_sign": null
            }],
            "menu_order": 9,
            "menu_action": 1,
            "menu_sign": null
        }],
        "deptRoles": [{
            "dept_id": 1,
            "dept_name": "事业部",
            "dept_fid": null,
            "depts": null,
            "roles": [{
                "dept": null,
                "menus": null,
                "role_NAME": "事业经理",
                "role_ID": "28fbb66259af47ddb79c45b8b4f2f07c"
            }, {
                "dept": null,
                "menus": null,
                "role_NAME": "事业部长",
                "role_ID": "cf55b49eb314446aabb3cc47e0e933a7"
            }, {
                "dept": null,
                "menus": null,
                "role_NAME": "中级开发工程师",
                "role_ID": "981124cbcf394e8cb3eb29b67ef92198"
            }, {"dept": null, "menus": null, "role_NAME": "产品经理", "role_ID": "041ed646819048cb8acbf3343f69c97d"}],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 37,
            "dept_name": "苟利国家生死以",
            "dept_fid": null,
            "depts": null,
            "roles": [{
                "dept": null,
                "menus": null,
                "role_NAME": "测试角色名称",
                "role_ID": "eb2388f307d14481a57463e3dc1df49c"
            }, {"dept": null, "menus": null, "role_NAME": "测试角色名称二", "role_ID": "8f72307d9dbe4b2983a7a69789bf7c23"}],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 50,
            "dept_name": "致",
            "dept_fid": 41,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 48,
            "dept_name": "最",
            "dept_fid": 39,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 44,
            "dept_name": "暴",
            "dept_fid": 35,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 36,
            "dept_name": "再竭衰庸定不支",
            "dept_fid": null,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 41,
            "dept_name": "戏与山妻谈故事",
            "dept_fid": null,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 51,
            "dept_name": "命",
            "dept_fid": 42,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 45,
            "dept_name": "力",
            "dept_fid": 36,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 14,
            "dept_name": "事业部一组",
            "dept_fid": 1,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 49,
            "dept_name": "为",
            "dept_fid": 40,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 47,
            "dept_name": "蛤",
            "dept_fid": 38,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 38,
            "dept_name": "岂因祸福避趋之",
            "dept_fid": null,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 46,
            "dept_name": "膜",
            "dept_fid": 37,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 39,
            "dept_name": "谪居正是君恩厚",
            "dept_fid": null,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 40,
            "dept_name": "养拙刚于戍卒宜",
            "dept_fid": null,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 35,
            "dept_name": "力微任重久神疲",
            "dept_fid": null,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }, {
            "dept_id": 42,
            "dept_name": "试吟断送老头皮",
            "dept_fid": null,
            "depts": null,
            "roles": [],
            "users": null,
            "system_NAME": null,
            "system_ID": null,
            "project": null
        }]
    }
}